before_script:
- bundle install
- chmod +x ./script/cibuild
script: "./script/cibuild"
cache: bundler
language: ruby
sudo: false
rvm:
- 2.3.0
branches:
  only:
  - gh-pages
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: HA/6nIJeiUjgCE+Z/6AMerDlnbty5XuQFJZ1zK/3c1dcjXLKCf3t1gR5iCK7j+qNIKW8m8Ir33jXkHwy4OP04frwnXjEFkuQpS2cuk/YlGSnl8/oanK0SwK/p/VmXX0FoBiVqcuc72U2loimkBZSMqa0jD8EeLQlOqstX7rS/zvlIHo/NAPBarnZWEKYqVXboDDCxKhvVdTn6YT+7/UyeABnVXw8L+0wprYu/aoi10GPN5x5zmjMaNg9/HPJ5dIrPH5kG/wuDsCoFzKBtK2dCTJ2iQ16ZawA81Vq9i7RD106chkyRPIn4o3oxMJvwvH4nZclf3h5OtAu24+TUoLkARZWvXuhOMjdLeQmZgAifl5oSJfSR1f8eIXaca4IBnXu4GhsDl4rev9PLMnF0yJqt/QLo+y5a/EINSGD2PZvVsPL2lLWrlBRDcT7wF5LLxzPRmnUBckz4OW373sMQWBvrs+0j4lFwj+euIe1XWvgWxdAuTvl72pQM3DTVCXoPK7FE0FcTMbNYXP7yfmohOwZDtRVKbE4WOMI6xT9fz58txOe36Hoe1EB2uvfAgj6TESC9oLK9HaFNQ848oIvNoiTo5BVulxB6k85zlpCwuweURksgoTgnNr/OqeIct7OJ7NRGNrtQf5WZSV1uD4roijf1i51zzmxkZjr/+11HMgQPKs=
  - secure: HFBr5/TfDnwNcepmqk9NFKLf9SKLZ35XVTacR3HUNFyck1wZpiYJXs3Jj3kfcCmlWzv2y5nrusEc2HzIR4L/UKWIgMuV8G+rZQKyckitTEDTq3FACH5B5MPo4SmESoCf4cU0NAIRJpPk8pCNu2wasm9PP3HHDP0pH/wFygNhFwqrO+QluIhEtJ0ys2IQ/L6xW873B+Ylx0lDa6/rKCfZd6MumdDYRNq34KSST+ni2o3hfDWiJvIfDx7tkAgQRLg4MywjNED+g19QSZfjaQG6v3U6Ias4KmNNh5LV4VDVzQTiVt2DnBq8JQ9ZjlcNH3JOxxL85q6YO5joo/c0jVKATbBccmhP2o0kDF4XkeEJVXk2Sa3EmK5rK6uVHNOq2KX7oZ2Vk9goSdhp2xVS+L96F5ICbTae0JvOLpXsO8QksdU+crdeQHbDm0Gc4YEetdGzc8sDRgtXIJWtCfeJzUeh4QXqdUJ7zt5YmftJd3pKxGab1kcZ7C/SI0bKIeairh3LYKAfaQqyw9vlkN0Axqf+fGzXVRGUeGhMg3cHwJ6Gg987jdsUZGb4wLaxk2jwTKinNT5MXvWYxrIQ1Qp6mTMTpJrW6/HzV8Jn29w+HfbacK4WFBXH3m+3nS22JdMPQcMa9JAKHIxg26Z3bIi5lhFfxsu861U8QCmaxgKPTfeb75k=
