# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Blog from my cave"
description: > # this means to ignore newlines until "email:"

email: dev@mrmandeep.me
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/header-background.jpg"

name: 'Mandeep Singh'
author: 'Singh'
author_image: "/assets/images/author.jpg"

paginate:	5
exclude: [vendor]
url: "https://blog.mrmandeep.me" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dMandeepSingh'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/daxlab
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/mandeep-singh-sawhney-36aa2b6b
    desc:	Connect with me on linkedin
    share_url:
    share_title:
    share_link:

  - icon:	twitter
    url:	https://twitter.com/dMandeepSingh
    desc:   Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/mrmandy007
    desc:   Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	medium
    url:	https://medium.com/@mrmandeep
    desc:   Follow me on medium
    share_url:
    share_title:
    share_link:

  - icon:	envelope
    url:    mailto:dev@mrmandeep.me
    desc:
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
